name: Run on Container
on: push

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.13.6
    
    steps:
      - name: Print terraform version
        run: terraform -v
