name: Test Strategy
on: push

jobs:
  test-strategy:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 6
          - 8
          - 10
        exclude:
          - os: windows-latest
        include:
          - os: ubuntu-latest
            node-version: 8
            new-variable: 'true'
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Log Node Version
        run: node -v
        
      - name: New Variable
        if: ${{ matrix.new-variable == 'true' }}
        run: echo ${{ matrix.new-variable }}
        
